title: Upstream Digest Server
description: Chrome Release Notes Digest Collection
# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
baseurl: "/upstream-digest-server"
url: "https://novac42.github.io"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

collections:
  digests:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default