title: Chrome Release Digests
description: Comprehensive Chrome web platform release notes with version selection
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
