defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
description: Comprehensive Chrome web platform release notes with version selection
plugins:
- jekyll-feed
- jekyll-sitemap
theme: minima
title: Chrome Release Digests
